version: "3.8"

services:

  db:
    image: mysql:8.2.0
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      -  ./.docker/db/data:/var/lib/mysql/
    networks:
      - web

  backend:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html/backend
    depends_on:
      - db
    networks:
      - web

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
    volumes:
      - ./.docker/nginx/log:/var/log/nginx
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:
    driver: bridge
